### PR TITLE
Merge latest updates for deployment

### PR DESCRIPTION
**Pull request by nabury**
Version number incremented and updates edited on ui.R

### CODE REVIEW

**Comment by JanionNevill** [comment]
Can you update `CITATION.cff`:
- To be the updated version
- To add me to the author list
- To correct the names of you and Yiqiao (family names and given names swapped I think)

**Comment by JanionNevill** [comment]
Have you tested the app to see that all is working as expected?

**Review by JanionNevill — CHANGES_REQUESTED** [review]
I started a release process document and I've uploaded it to the *R Shiny* team. Please take a look at that and add anything that I've missed.

**Comment by nabury** [comment]
> Have you tested the app to see that all is working as expected?

I've had a manual check through and all seems fine but will check again after merging.

**Review by JanionNevill — APPROVED** [review]

**Pull request merged**
